In [2]:
import pandas as pd

amazon_df = pd.read_csv("amazon.csv", encoding="latin-1")

amazon_df = amazon_df[
    ["Product Name", "Category", "Selling Price", "Image"]
]

amazon_df.head()

,Product Name,Category,Selling Price,Image
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,$237.68,https://images-na.ssl-images-amazon.com/images...
1,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,$99.95,https://images-na.ssl-images-amazon.com/images...
2,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,$34.99,https://images-na.ssl-images-amazon.com/images...
3,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,$28.91,https://images-na.ssl-images-amazon.com/images...
4,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,$17.49,https://images-na.ssl-images-amazon.com/images...

In [52]:
amazon_df.isnull().sum()

Product Name         0
Brand Name       10002
Category           830
Selling Price      107
Image                0
Product Url          0
dtype: int64

In [6]:
amazon_df = amazon_df.dropna()
amazon_df.shape

(9066, 4)

In [8]:
amazon_df["tags"] = (
    amazon_df["Product Name"].astype(str) + " " +
    amazon_df["Category"].astype(str)
)

amazon_df.head()

,Product Name,Category,Selling Price,Image,tags
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,$237.68,https://images-na.ssl-images-amazon.com/images...,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib..."
1,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,$99.95,https://images-na.ssl-images-amazon.com/images...,"Electronic Snap Circuits Mini Kits Classpack, ..."
2,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,$34.99,https://images-na.ssl-images-amazon.com/images...,3Doodler Create Flexy 3D Printing Filament Ref...
3,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,$28.91,https://images-na.ssl-images-amazon.com/images...,Guillow Airplane Design Studio with Travel Cas...
4,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,$17.49,https://images-na.ssl-images-amazon.com/images...,Woodstock- Collage 500 pc Puzzle Toys & Games ...

In [42]:
amazon_df = amazon_df[[
    "Product Name",
    "Category",
    "Selling Price",
    "Image",
    "Brand Name",
    "Product Url"
]]

KeyError: "['Brand Name'] not in index"

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = cv.fit_transform(amazon_df["tags"]).toarray()

print(vectors.shape)

(9066, 5000)

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

print(similarity.shape)

(9066, 9066)

In [14]:
def recommend(product_name):
    index = amazon_df[amazon_df["Product Name"] == product_name].index[0]

    distances = sorted(
        list(enumerate(similarity[index])),
        reverse=True,
        key=lambda x: x[1]
    )

    for i in distances[1:6]:
        print("--------------------------------")
        print("Product :", amazon_df.iloc[i[0]]["Product Name"])
        print("Category:", amazon_df.iloc[i[0]]["Category"])
        print("Price   :", amazon_df.iloc[i[0]]["Selling Price"])

In [16]:
recommend(amazon_df.iloc[0]["Product Name"])

--------------------------------
Product : Rayne Longboards Demonseed Longboard Complete
Category: Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards
Price   : $249.95
--------------------------------
Product : DB Longboards Contra Drop Deck Maple Longboard Complete
Category: Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards
Price   : $80.96
--------------------------------
Product : PARADISE The Mallows Kicktail Complete Longboard
Category: Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards
Price   : $112.19
--------------------------------
Product : DB Longboards Phase 38" Maple Drop Through Longboard
Category: Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards
Price   : $134.82
--------------------------------
Product : Retrospec Rift Drop-Through Longboard Skateboard Complete
Category: Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards
Price   : Total price:

In [18]:
import pickle

pickle.dump(amazon_df, open("products.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

print("Files Saved Successfully!")

Files Saved Successfully!

In [21]:
amazon_df.columns.tolist()

['Product Name', 'Category', 'Selling Price', 'Image', 'tags']

In [23]:
amazon_df.columns.tolist()

['Product Name', 'Category', 'Selling Price', 'Image', 'tags']

In [25]:
import pandas as pd

full_df = pd.read_csv("amazon.csv", encoding="latin-1")

print(full_df.columns.tolist())

['Uniq Id', 'Product Name', 'Brand Name', 'Asin', 'Category', 'Upc Ean Code', 'List Price', 'Selling Price', 'Quantity', 'Model Number', 'About Product', 'Product Specification', 'Technical Details', 'Shipping Weight', 'Product Dimensions', 'Image', 'Variants', 'Sku', 'Product Url', 'Stock', 'Product Details', 'Dimensions', 'Color', 'Ingredients', 'Direction To Use', 'Is Amazon Seller', 'Size Quantity Variant', 'Product Description']

In [27]:
amazon_df = pd.read_csv("amazon.csv", encoding="latin-1")

amazon_df = amazon_df[[
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url"
]]

amazon_df = amazon_df.dropna()

amazon_df.head()

Empty DataFrame
Columns: [Product Name, Brand Name, Category, Selling Price, Image, Product Url]
Index: []

In [29]:
print(amazon_df.shape)

amazon_df.isnull().sum()

(0, 6)

Product Name     0
Brand Name       0
Category         0
Selling Price    0
Image            0
Product Url      0
dtype: int64

In [31]:
full_df = pd.read_csv("amazon.csv", encoding="latin-1")

print(full_df[[
    "Brand Name",
    "Product Url",
    "Image"
]].isnull().sum())

Brand Name     10002
Product Url        0
Image              0
dtype: int64

In [33]:
import pandas as pd

amazon_df = pd.read_csv("amazon.csv", encoding="latin-1")

amazon_df = amazon_df[[
    "Product Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url"
]]

amazon_df = amazon_df.dropna()

print(amazon_df.shape)

amazon_df.head()

(9066, 5)

,Product Name,Category,Selling Price,Image,Product Url
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,$237.68,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/DB-Longboards-CoreFlex-...
1,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,$99.95,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Electronic-Circuits-Cla...
2,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,$34.99,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/3Doodler-Plastic-Innova...
3,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,$28.91,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Guillow-Airplane-Design...
4,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,$17.49,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Woodstock-Collage-500-p...

In [35]:
amazon_df["tags"] = amazon_df["Category"]

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

vectors = tfidf.fit_transform(amazon_df["tags"])

print(vectors.shape)

(9066, 1135)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

print(similarity.shape)

(9066, 9066)

In [39]:
import pickle

pickle.dump(amazon_df, open("products.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

print("✅ Files Saved Successfully!")

✅ Files Saved Successfully!

In [41]:
import os

print(os.listdir())

['amazon.csv', 'Amazon_Recommendation.ipynb', 'app.py', 'products.pkl', 'product_recommendation.ipynb', 'similarity.pkl', 'train.csv']

In [44]:
import pandas as pd

full_df = pd.read_csv("amazon.csv", encoding="latin-1")

print(full_df.columns.tolist())

['Uniq Id', 'Product Name', 'Brand Name', 'Asin', 'Category', 'Upc Ean Code', 'List Price', 'Selling Price', 'Quantity', 'Model Number', 'About Product', 'Product Specification', 'Technical Details', 'Shipping Weight', 'Product Dimensions', 'Image', 'Variants', 'Sku', 'Product Url', 'Stock', 'Product Details', 'Dimensions', 'Color', 'Ingredients', 'Direction To Use', 'Is Amazon Seller', 'Size Quantity Variant', 'Product Description']

In [46]:
full_df = pd.read_csv("amazon.csv", encoding="latin-1")

In [48]:
amazon_df = full_df[[
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url"
]]

In [50]:
for col in full_df.columns:
    print(col)

Uniq Id
Product Name
Brand Name
Asin
Category
Upc Ean Code
List Price
Selling Price
Quantity
Model Number
About Product
Product Specification
Technical Details
Shipping Weight
Product Dimensions
Image
Variants
Sku
Product Url
Stock
Product Details
Dimensions
Color
Ingredients
Direction To Use
Is Amazon Seller
Size Quantity Variant
Product Description

In [51]:
full_df = pd.read_csv("amazon.csv", encoding="latin-1")

amazon_df = full_df[[
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url"
]]

amazon_df.head()

,Product Name,Brand Name,Category,Selling Price,Image,Product Url
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",NaN,Sports & Outdoors | Outdoor Recreation | Skate...,$237.68,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/DB-Longboards-CoreFlex-...
1,"Electronic Snap Circuits Mini Kits Classpack, ...",NaN,Toys & Games | Learning & Education | Science ...,$99.95,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Electronic-Circuits-Cla...
2,3Doodler Create Flexy 3D Printing Filament Ref...,NaN,Toys & Games | Arts & Crafts | Craft Kits,$34.99,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/3Doodler-Plastic-Innova...
3,Guillow Airplane Design Studio with Travel Cas...,NaN,Toys & Games | Hobbies | Models & Model Kits |...,$28.91,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Guillow-Airplane-Design...
4,Woodstock- Collage 500 pc Puzzle,NaN,Toys & Games | Puzzles | Jigsaw Puzzles,$17.49,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Woodstock-Collage-500-p...

In [53]:
import pickle

pickle.dump(amazon_df, open("products.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

print("✅ Files Saved Successfully!")

✅ Files Saved Successfully!

In [54]:
amazon_df["tags"] = (
    amazon_df["Product Name"].fillna("") + " " +
    amazon_df["Brand Name"].fillna("") + " " +
    amazon_df["Category"].fillna("") + " " +
    full_df["About Product"].fillna("")
)

In [55]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

vectors = tfidf.fit_transform(amazon_df["tags"])

print(vectors.shape)

(10002, 26183)

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

print(similarity.shape)

(10002, 10002)

In [57]:

import pickle

pickle.dump(amazon_df, open("products.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))

print("✅ Files Saved Successfully!")

✅ Files Saved Successfully!

In [58]:
amazon_df = full_df[[
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url",
    "About Product",
    "tags"
]]

KeyError: "['tags'] not in index"

In [59]:
amazon_df = full_df[[
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "Image",
    "Product Url",
    "About Product"
]]

In [1]:
amazon_df["tags"] = (
    amazon_df["Product Name"].fillna("") + " " +
    amazon_df["Brand Name"].fillna("") + " " +
    amazon_df["Category"].fillna("") + " " +
    amazon_df["About Product"].fillna("")
)

NameError: name 'amazon_df' is not defined

In [3]:
import pickle

products = pickle.load(open("products.pkl", "rb"))

print(products.shape)
print(products.columns)
print(products.head())

(10002, 7)
Index(['Product Name', 'Brand Name', 'Category', 'Selling Price', 'Image',
       'Product Url', 'tags'],
      dtype='str')
                                        Product Name  Brand Name  \
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...         NaN
1  Electronic Snap Circuits Mini Kits Classpack, ...         NaN
2  3Doodler Create Flexy 3D Printing Filament Ref...         NaN
3  Guillow Airplane Design Studio with Travel Cas...         NaN
4                   Woodstock- Collage 500 pc Puzzle         NaN

                                            Category Selling Price  \
0  Sports & Outdoors | Outdoor Recreation | Skate...       $237.68
1  Toys & Games | Learning & Education | Science ...        $99.95
2          Toys & Games | Arts & Crafts | Craft Kits        $34.99
3  Toys & Games | Hobbies | Models & Model Kits |...        $28.91
4            Toys & Games | Puzzles | Jigsaw Puzzles        $17.49

                                               Image  \
0  https://images-na.ssl-images-amazon.com/images...
1  https://images-na.ssl-images-amazon.com/images...
2  https://images-na.ssl-images-amazon.com/images...
3  https://images-na.ssl-images-amazon.com/images...
4  https://images-na.ssl-images-amazon.com/images...

                                         Product Url  \
0  https://www.amazon.com/DB-Longboards-CoreFlex-...
1  https://www.amazon.com/Electronic-Circuits-Cla...
2  https://www.amazon.com/3Doodler-Plastic-Innova...
3  https://www.amazon.com/Guillow-Airplane-Design...
4  https://www.amazon.com/Woodstock-Collage-500-p...

                                                tags
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...
1  Electronic Snap Circuits Mini Kits Classpack, ...
2  3Doodler Create Flexy 3D Printing Filament Ref...
3  Guillow Airplane Design Studio with Travel Cas...
4  Woodstock- Collage 500 pc Puzzle  Toys & Games...

In [5]:
import pickle

similarity = pickle.load(open("similarity.pkl","rb"))

print(type(similarity))
print(len(similarity))
print(len(similarity[0]))

<class 'numpy.ndarray'>
10002
10002

In [6]:
index = products[products["Product Name"] == product_name].index[0]

distances = sorted(
    list(enumerate(similarity[index])),
    reverse=True,
    key=lambda x: x[1]
)

for i in distances[1:6]:
    print(products.iloc[i[0]]["Product Name"])

NameError: name 'product_name' is not defined

In [8]:
product_name = products.iloc[0]["Product Name"]

print(product_name)

DB Longboards CoreFlex Crossbow 41" Bamboo Fiberglass Longboard Complete

In [9]:
index = products[products["Product Name"] == product_name].index[0]

distances = sorted(
    list(enumerate(similarity[index])),
    reverse=True,
    key=lambda x: x[1]
)

for i in distances[1:6]:
    print(products.iloc[i[0]]["Product Name"])

DB Longboards Phase 38" Maple Drop Through Longboard
DB Longboards Contra Drop Deck Maple Longboard Complete
Moose Bamboo Kicktail/Kryptonics Longboard
Rayne Longboards Demonseed Longboard Complete
Rayne Longboards Minotaur 34" Double Kick Cruiser Skateboard

In [10]:
print(full_df.shape)

print(full_df.columns.tolist())

NameError: name 'full_df' is not defined

In [11]:
import pandas as pd

# Load Dataset
full_df = pd.read_csv("amazon.csv", encoding="latin-1")

# Dataset Information
print("="*60)
print("DATASET SHAPE")
print("="*60)
print(full_df.shape)

print("\n")

print("="*60)
print("COLUMN NAMES")
print("="*60)
print(full_df.columns.tolist())

print("\n")

# Select Required Columns
amazon_df = full_df[
    [
        "Product Name",
        "Brand Name",
        "Category",
        "Selling Price",
        "About Product",
        "Image",
        "Product Url"
    ]
].copy()

# Fill Missing Values
amazon_df["Product Name"] = amazon_df["Product Name"].fillna("")
amazon_df["Brand Name"] = amazon_df["Brand Name"].fillna("")
amazon_df["Category"] = amazon_df["Category"].fillna("")
amazon_df["About Product"] = amazon_df["About Product"].fillna("")
amazon_df["Image"] = amazon_df["Image"].fillna("")
amazon_df["Product Url"] = amazon_df["Product Url"].fillna("")
amazon_df["Selling Price"] = amazon_df["Selling Price"].fillna("")

# Create Tags
amazon_df["tags"] = (
    amazon_df["Product Name"] + " " +
    amazon_df["Brand Name"] + " " +
    amazon_df["Category"] + " " +
    amazon_df["About Product"]
)

print("="*60)
print("FINAL DATAFRAME")
print("="*60)

print("Shape :", amazon_df.shape)

print("\nColumns :")
print(amazon_df.columns.tolist())

print("\nFirst 5 Rows :")
print(amazon_df.head())

print("\n")

print("="*60)
print("MISSING VALUES")
print("="*60)

print(amazon_df.isnull().sum())

============================================================
DATASET SHAPE
============================================================
(10002, 28)


============================================================
COLUMN NAMES
============================================================
['Uniq Id', 'Product Name', 'Brand Name', 'Asin', 'Category', 'Upc Ean Code', 'List Price', 'Selling Price', 'Quantity', 'Model Number', 'About Product', 'Product Specification', 'Technical Details', 'Shipping Weight', 'Product Dimensions', 'Image', 'Variants', 'Sku', 'Product Url', 'Stock', 'Product Details', 'Dimensions', 'Color', 'Ingredients', 'Direction To Use', 'Is Amazon Seller', 'Size Quantity Variant', 'Product Description']


============================================================
FINAL DATAFRAME
============================================================
Shape : (10002, 8)

Columns :
['Product Name', 'Brand Name', 'Category', 'Selling Price', 'About Product', 'Image', 'Product Url', 'tags']

First 5 Rows :
                                        Product Name Brand Name  \
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...
1  Electronic Snap Circuits Mini Kits Classpack, ...
2  3Doodler Create Flexy 3D Printing Filament Ref...
3  Guillow Airplane Design Studio with Travel Cas...
4                   Woodstock- Collage 500 pc Puzzle

                                            Category Selling Price  \
0  Sports & Outdoors | Outdoor Recreation | Skate...       $237.68
1  Toys & Games | Learning & Education | Science ...        $99.95
2          Toys & Games | Arts & Crafts | Craft Kits        $34.99
3  Toys & Games | Hobbies | Models & Model Kits |...        $28.91
4            Toys & Games | Puzzles | Jigsaw Puzzles        $17.49

                                       About Product  \
0  Make sure this fits by entering your model num...
1  Make sure this fits by entering your model num...
2  Make sure this fits by entering your model num...
3  Make 8 different Planes at one time. | Experim...
4  Make sure this fits by entering your model num...

                                               Image  \
0  https://images-na.ssl-images-amazon.com/images...
1  https://images-na.ssl-images-amazon.com/images...
2  https://images-na.ssl-images-amazon.com/images...
3  https://images-na.ssl-images-amazon.com/images...
4  https://images-na.ssl-images-amazon.com/images...

                                         Product Url  \
0  https://www.amazon.com/DB-Longboards-CoreFlex-...
1  https://www.amazon.com/Electronic-Circuits-Cla...
2  https://www.amazon.com/3Doodler-Plastic-Innova...
3  https://www.amazon.com/Guillow-Airplane-Design...
4  https://www.amazon.com/Woodstock-Collage-500-p...

                                                tags
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...
1  Electronic Snap Circuits Mini Kits Classpack, ...
2  3Doodler Create Flexy 3D Printing Filament Ref...
3  Guillow Airplane Design Studio with Travel Cas...
4  Woodstock- Collage 500 pc Puzzle  Toys & Games...


============================================================
MISSING VALUES
============================================================
Product Name     0
Brand Name       0
Category         0
Selling Price    0
About Product    0
Image            0
Product Url      0
tags             0
dtype: int64

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# TF-IDF Vectorizer
tfidf = TfidfVectorizer(stop_words="english")

vectors = tfidf.fit_transform(amazon_df["tags"])

print("TF-IDF Shape:", vectors.shape)

# Cosine Similarity
similarity = cosine_similarity(vectors)

print("Similarity Shape:", similarity.shape)

# Save DataFrame
pickle.dump(amazon_df, open("products.pkl", "wb"))

# Save Similarity Matrix
pickle.dump(similarity, open("similarity.pkl", "wb"))

print("\n✅ products.pkl created successfully")
print("✅ similarity.pkl created successfully")

TF-IDF Shape: (10002, 26183)
Similarity Shape: (10002, 10002)

✅ products.pkl created successfully
✅ similarity.pkl created successfully

In [ ]:
import streamlit as st
import pandas as pd
import pickle
from pathlib import Path

st.set_page_config(
    page_title="Amazon Product Recommendation System",
    page_icon="🛒",
    layout="wide"
)

st.title("🛒 Amazon Product Recommendation System")
st.write("Find similar Amazon products using Machine Learning.")
st.divider()

PRODUCT_FILE = "products.pkl"
SIMILARITY_FILE = "similarity.pkl"

if not Path(PRODUCT_FILE).exists():
    st.error("products.pkl file not found.")
    st.stop()

if not Path(SIMILARITY_FILE).exists():
    st.error("similarity.pkl file not found.")
    st.stop()

try:
    with open(PRODUCT_FILE, "rb") as f:
        products = pickle.load(f)

    with open(SIMILARITY_FILE, "rb") as f:
        similarity = pickle.load(f)

except Exception as e:
    st.error(f"Unable to load pickle files.\n\n{e}")
    st.stop()

required_columns = [
    "Product Name",
    "Brand Name",
    "Category",
    "Selling Price",
    "About Product",
    "Image",
    "Product Url"
]

missing = [c for c in required_columns if c not in products.columns]

if missing:
    st.error(f"Missing Columns:\n{missing}")
    st.stop()

st.sidebar.header("Filter Products")

categories = sorted(products["Category"].dropna().unique())

selected_category = st.sidebar.selectbox(
    "Select Category",
    ["All"] + list(categories)
)

if selected_category == "All":
    filtered_products = products.copy()
else:
    filtered_products = products[
        products["Category"] == selected_category
    ]

if filtered_products.empty:
    st.warning("No products found.")
    st.stop()

selected_product = st.selectbox(
    "🔍 Search Product",
    filtered_products["Product Name"].tolist()
)

recommend_btn = st.button("🚀 Recommend Products")


def recommend_products(product_name, n=5):

    idx = products.index[
        products["Product Name"] == product_name
    ]

    if len(idx) == 0:
        return pd.DataFrame()

    index = idx[0]

    scores = list(enumerate(similarity[index]))

    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )

    recommendation_index = []

    for i, score in scores:

        if i == index:
            continue

        recommendation_index.append(i)

        if len(recommendation_index) == n:
            break

    return products.iloc[recommendation_index]


def show_image(url, width=200):

    try:
        if pd.notna(url) and str(url).startswith("http"):
            st.image(url, width=width)
        else:
            st.info("No Image Available")
    except:
        st.info("Image cannot be displayed")


if recommend_btn:

    product = products[
        products["Product Name"] == selected_product
    ]

    if product.empty:
        st.error("Product not found.")
        st.stop()

    product = product.iloc[0]

    st.subheader("Selected Product")

    col1, col2 = st.columns([1, 2])

    with col1:
        show_image(product["Image"], 250)

    with col2:

        st.markdown(f"### {product['Product Name']}")
        st.write("**Brand:**", product["Brand Name"])
        st.write("**Category:**", product["Category"])
        st.write("**Price:**", product["Selling Price"])
        st.write(product["About Product"])

        if pd.notna(product["Product Url"]):
            st.link_button("🛒 Buy on Amazon", product["Product Url"])

    st.divider()

    st.subheader("Recommended Products")

    recommendations = recommend_products(selected_product)

    if recommendations.empty:
        st.warning("No recommendations found.")

    else:

        for _, item in recommendations.iterrows():

            c1, c2 = st.columns([1, 3])

            with c1:
                show_image(item["Image"], 150)

            with c2:

                st.markdown(f"#### {item['Product Name']}")
                st.write("**Brand:**", item["Brand Name"])
                st.write("**Category:**", item["Category"])
                st.write("**Price:**", item["Selling Price"])
                st.write(item["About Product"])

                if pd.notna(item["Product Url"]):
                    st.link_button(
                        "🛒 Buy on Amazon",
                        item["Product Url"],
                        key=f"buy_{_}"
                    )

            st.divider()

2026-07-24 07:41:13.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:13.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2026-07-24 07:41:14.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-24 07:41:14.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.